### PR TITLE
Fix gaps / inconsistencies in BACKUP / RESTORE device type

### LINKED ISSUE #29: Incorrect Syntax near URL in Restore Database statement
- SqlPackage or DacFx Version: 
- .NET Framework (Windows-only) or .NET Core: 
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Try to build a statement in VS that has Restore Database with URL then it will shows the below syntax error from ScriptDom Parserimage
**Did this occur in prior versions?  If not - which version(s) did it work in?** Yes

(DacFx/SqlPackage/SSMS/Azure Data Studio)

### PR DESCRIPTION
**Pull request by arvindshmicrosoft**
Originally created just to fix #29, but in the process fixed subtle issues with VirtualDevice and DatabaseSnapshot device types as well.

* Add the URL device type for use with BACKUP and RESTORE statements for 110 parser and above. URL backups were introduced with SQL Server 2012. Also updated the ScriptGenerator to ensure URL devices are correctly scripted.

* Add version constraints for device types DatabaseSnapshot and VirtualDevice, both of which are only supported for SQL 2005+.

* Remove dead code related to Disk device type in grammar 90 and above. In all grammars other than 80, the different device types are handled by the DeviceTypesHelper class, so the special case in the grammar for Disk device type was never used. In 80 grammar though, the Disk device type is not treated as an indentifier and hence the special case for Disk is still needed.

* Add regression tests for device types URL, VIRTUAL_DEVICE and DATABASE_SNAPSHOT, and for good measure, DISK as well

### CODE REVIEW

File: Test/SqlDom/BackupRestoreRegressionTests.cs [hunk 1]
```diff
@@ -0,0 +1,156 @@
+﻿using System.Collections.Generic;
+using Microsoft.SqlServer.TransactSql.ScriptDom;
+using Microsoft.VisualStudio.TestTools.UnitTesting;
+using SqlStudio.Tests.AssemblyTools.TestCategory;
+
+namespace SqlStudio.Tests.UTSqlScriptDom
+{
+    using System;
+    using System.IO;
```
Comment (zijchen) [inline Test/SqlDom/BackupRestoreRegressionTests.cs:9]: nit: Move these to the top of the file

File: Test/SqlDom/BackupRestoreRegressionTests.cs [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+                        // for these parser versions we expect success
+                        Assert.AreEqual(0, errors.Count);
+                        Assert.IsTrue(fragment is TSqlScript);
+                        Assert.IsTrue(fragment.Batches[0].Statements[0] is BackupStatement);
+                        Assert.IsTrue(fragment.Batches[0].Statements[1] is RestoreStatement);
+                    }
+                }
+            }, true);
+        }
+	}
```
Comment (zijchen) [inline Test/SqlDom/BackupRestoreRegressionTests.cs:155]: nit: indentation

File: Test/SqlDom/BackupRestoreRegressionTests.cs [hunk 3]
```diff
@@ -0,0 +1,156 @@
...
+using Microsoft.VisualStudio.TestTools.UnitTesting;
+using SqlStudio.Tests.AssemblyTools.TestCategory;
+
+namespace SqlStudio.Tests.UTSqlScriptDom
+{
+    using System;
+    using System.IO;
+
+    public partial class SqlDomTests
+	{
```
Comment (zijchen) [inline Test/SqlDom/BackupRestoreRegressionTests.cs:12]: nit: indentation

**Review by zijchen — APPROVED** [review]

File: Test/SqlDom/BackupRestoreRegressionTests.cs (hunk 1 above)
Comment (arvindshmicrosoft) [reply Test/SqlDom/BackupRestoreRegressionTests.cs]: Thanks! - addressed in 2926e5154dc4f8147178f2660b3cf2cd7b99095b.

File: Test/SqlDom/BackupRestoreRegressionTests.cs (hunk 2 above)
Comment (arvindshmicrosoft) [reply Test/SqlDom/BackupRestoreRegressionTests.cs]: Thanks! - addressed in 2926e5154dc4f8147178f2660b3cf2cd7b99095b.

File: Test/SqlDom/BackupRestoreRegressionTests.cs (hunk 3 above)
Comment (arvindshmicrosoft) [reply Test/SqlDom/BackupRestoreRegressionTests.cs]: Thanks! - addressed in 2926e5154dc4f8147178f2660b3cf2cd7b99095b.

**Review by barbaravaldez — APPROVED** [review]
