### PR TITLE
Fixing a parsing issue with procedure and atomic block

### LINKED ISSUE #31: wrong parsing results for natively compiled stored procedures
- DacFx Version: Nuget latest (160.6161.0)
- .NET: 6.0.301
- Environment (local platform and source/target platforms): linux-x64

**Steps to Reproduce:**

1. parse create statement of natively compiled stored procedure
2. check resulting ProcedureStatementBody.StatementList.StartColumn

sample code (place in file.fsx, then run dotnet fsi --exec file.fsx):
`#r "nuget: Microsoft.SqlServer.DacFx"

open System.IO
open System.Collections.Generic
open Microsoft.SqlServer.TransactSql.ScriptDom

let parse sql =
  let parser = TSql160Parser(false)
  use textReader = new StringReader(sql) :> TextReader
  let mutable errors : IList<_> = Unchecked.defaultof<IList<_>>
  let res = parser.Parse(textReader, &errors)
  match errors.Count with
  | 0 -> res
  | _ -> failwith $"parse error\n\n{sql}"

let visitor = {
  new TSqlFragmentVisitor() with
  override this.Visit(proc:ProcedureStatementBody) =
    match Option.ofObj proc.StatementList with
    | Some sl -> printfn $"line: {sl.StartLine} column: {sl.StartColumn}"
    | _ -> ()
}

let proc = """
CREATE PROCEDURE dbo.usp_add_kitchen @dept_id INT, @kitchen_count INT NOT NULL
WITH EXECUTE AS OWNER, SCHEMABINDING, NATIVE_COMPILATION
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'us_english')

UPDATE dbo.Departments
SET kitchen_count = ISNULL(kitchen_count, 0) + @kitchen_count
WHERE ID = @dept_id
END;
"""

let parsed = parse proc
parsed.Accept(visitor)
`

result is:

line: 5 column: 50

which points to value of first ATOMIC WITH option, "SNAPSHOT" here

expected result:

line: 5 column: 1

### PR DESCRIPTION
**Pull request by llali**
fixes #31

### CODE REVIEW

File: Test/SqlDom/TSqlParserTest.cs [hunk 1]
```diff
@@ -426,6 +426,37 @@ public void OpenRowsetBulkWithThreeFiles()
             ));
         }
 
+        [TestMethod]
+        [Priority(0)]
+        [Timeout(GlobalConstants.DefaultTestTimeout)]
+        [SqlStudioTestCategory(Category.UnitTest)]
```
Comment (zijchen) [inline Test/SqlDom/TSqlParserTest.cs:432]: You can add a test to [Only120SyntaxTests](https://github.com/microsoft/SqlScriptDOM/blob/main/Test/SqlDom/Only120SyntaxTests.cs) (the version where the new grammar is introduced) instead of writing a new one. It runs parser and script generator. You just have to add a sql file to TestScripts and Baselines120 folder.

Comment (llali) [reply Test/SqlDom/TSqlParserTest.cs:432]: I add a test  there too but keep this one as well. the problem was with the startcolumn so I want to specifically verify it here

Comment (llali) [reply Test/SqlDom/TSqlParserTest.cs:432]: I verified those tests already verifying the atomic statement https://github.com/microsoft/SqlScriptDOM/blob/1c3a5cfe8289fda5c45f7b4f75fad8227508fc7f/Test/SqlDom/Baselines120/CreateProcedureStatementTests120.sql#L41

**Review by zijchen — APPROVED** [review]
